### ISSUE TITLE
New windows don't have shadows

### ISSUE THREAD

**Issue by MichielDerhaeg** [BlackCapCoder/compton#2]
New windows have to be resized or moved first in order for their shadows to be drawn.

**Comment by MichielDerhaeg** [comment]
I'm using XMonad btw

**Comment by BlackCapCoder** [comment]
Or you can switch back and forth to the workspace they are on apparently. Thank you for reporting it

**Comment by BlackCapCoder** [comment]
This issue does not occur with `spawn-center` disabled

**Comment by BlackCapCoder** [comment]
Fixed in 37e48fd

**Comment by BlackCapCoder** [comment]
Fixed in 37e48fd
