### ISSUE TITLE
[comment] Pull request to Compton

### ISSUE THREAD

**Issue by nkkollaw** [BlackCapCoder/compton#3]
First of all, you're a genius. Your fork works great.

I think Compton would immensely benefit from this, did you try a pull request?

**Comment by BlackCapCoder** [comment]
I fully intended to send a pull request, but I wanted to clean up my code first. Unfortunately compton is a 8-thousand-lines long file that is incredibly hard to read into, so I haven't found the motivation to do it yet.

**Comment by nkkollaw** [comment]
Ah, I see.

It's one single file!?
