### ISSUE TITLE
Part of border missing with BSPWM

### ISSUE THREAD

**Issue by Epictek** [BlackCapCoder/compton#8]
Very basic config:
```
backend = "glx";
paint-on-overlay = true;
glx-no-stencil = true;
vsync = "opengl-swc";
unredir-if-possible = true;
no-scale-down = true;
transition-length = 200;
# Opacity
detect-client-opacity = true;
# Window type settings
wintypes:
{
 tooltip = { shadow = false; };
};

```
![](https://0x0.st/sj9w.png)

**Comment by BlackCapCoder** [comment]
Is this also the case with regular compton?

**Comment by Epictek** [comment]
No, Tried with the original compton both built from source and the binary included in void repos and did not have this issue so it seems that it is exclusive to this fork.
